# -*- coding: utf-8 -*-
"""Regex Practice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zhFgvr7VmMssvbQA0StkdeBUp3h8IqYW

# Exract Email & Phone No. using Python & Regex
"""

import re

# Define regular expressions for Gmail IDs and Bangladeshi mobile numbers
gmail_regex = r'\b[A-Za-z0-9._%+-]+@gmail\.com\b'
bd_mobile_regex = r'\+8801\d{9}'

# Open the input file for reading
with open('/content/sample_data/input.txt', 'r') as input_file:
    # Read the file contents
    text = input_file.read()

    # Find all Gmail IDs in the text using the regular expression
    gmail_ids = re.findall(gmail_regex, text)

    # Write the Gmail IDs to the output file
    with open('gmail_id.txt', 'w') as gmail_file:
        for gmail_id in gmail_ids:
            gmail_file.write(gmail_id + '\n')

    # Find all Bangladeshi mobile numbers in the text using the regular expression
    bd_mobiles = re.findall(bd_mobile_regex, text)

    # Write the Bangladeshi mobile numbers to the output file
    with open('bd_mobile.txt', 'w') as bd_mobile_file:
        for bd_mobile in bd_mobiles:
            # Check if the mobile number is exactly 14 characters long
            if len(bd_mobile) == 14:
                bd_mobile_file.write(bd_mobile + '\n')